# Generated by Django 4.2.5 on 2023-09-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(max_length=10, null=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
    ]
