# Generated by Django 4.2.5 on 2023-09-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0002_custom_users_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_users',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
