# Generated by Django 4.1.7 on 2023-09-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0003_alter_custom_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_users',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
