# Generated by Django 4.2.5 on 2023-09-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0004_custom_users_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, null=True)),
                ('Category_quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('product_price', models.IntegerField()),
                ('product_image', models.CharField(max_length=255, null=True)),
                ('product_quantity', models.FloatField()),
                ('product_category', models.CharField(max_length=255, null=True)),
                ('product_descrip', models.CharField(max_length=255, null=True)),
                ('product_stock', models.FloatField()),
            ],
        ),
    ]
