# Generated by Django 4.2.5 on 2023-09-14 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0005_product_category_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Users_app.product_details'),
        ),
    ]
