# Generated by Django 4.1.7 on 2023-09-15 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0008_alter_product_details_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='product',
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Users_app.product_category'),
        ),
    ]
