# Generated by Django 4.1.7 on 2023-09-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0009_remove_product_category_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
