# Generated by Django 4.1.7 on 2023-09-18 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0012_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users_app.product_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users_app.custom_users')),
            ],
        ),
    ]
