# Generated by Django 4.1.7 on 2023-09-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0013_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('apartment_suite', models.CharField(blank=True, max_length=255, null=True)),
                ('town_city', models.CharField(max_length=255)),
                ('country_state', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
