# Generated by Django 4.1.7 on 2023-09-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0014_users_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_address',
            old_name='country_state',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='users_address',
            old_name='town_city',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='users_address',
            name='apartment_suite',
        ),
        migrations.RemoveField(
            model_name='users_address',
            name='postcode',
        ),
        migrations.AddField(
            model_name='users_address',
            name='apartment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='users_address',
            name='state',
            field=models.CharField(default='YourDefaultStateValue', max_length=255),
        ),
        migrations.AlterField(
            model_name='users_address',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
