# Generated by Django 4.1.7 on 2023-09-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0015_rename_country_state_users_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_address',
            name='apartment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
