# Generated by Django 4.2.5 on 2023-10-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0018_order_orderitem_order_cartitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='000000', max_length=100, unique=True),
        ),
    ]
