# Generated by Django 4.2.5 on 2023-10-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0019_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unique_order_number',
            field=models.CharField(default='0000', max_length=255),
        ),
    ]
