# Generated by Django 4.2.5 on 2023-10-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0021_deletedorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deleted_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users_app.deletedorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users_app.product_details')),
            ],
        ),
        migrations.AddField(
            model_name='deletedorder',
            name='products',
            field=models.ManyToManyField(blank=True, through='Users_app.DeletedOrderProduct', to='Users_app.product_details'),
        ),
    ]
