# Generated by Django 4.2.5 on 2023-10-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0024_rename_cartitems_deletedorder_deleteitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirm', 'Confirm'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='DeletedOrder',
        ),
    ]
