# Generated by Django 4.2.5 on 2023-10-12 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0025_alter_order_status_delete_deletedorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default='000000', max_length=100, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled')], default='Cancelled', max_length=50)),
                ('payment_method', models.CharField(max_length=20)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('cartitems', models.ManyToManyField(blank=True, to='Users_app.orderitem')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users_app.users_address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users_app.custom_users')),
            ],
        ),
    ]
