# Generated by Django 4.2.5 on 2023-10-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0026_cancelledorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirm', 'Confirm'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
