# Generated by Django 4.2.5 on 2023-10-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0027_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledorder',
            name='order_number',
            field=models.CharField(default='000000', max_length=100),
        ),
    ]
