# Generated by Django 4.2.5 on 2023-10-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0028_alter_cancelledorder_order_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancelledOrder',
        ),
    ]
