# Generated by Django 4.2.5 on 2023-10-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0031_product_offer_category_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_notes',
            field=models.TextField(default='no message', max_length=255),
        ),
    ]
