# Generated by Django 4.2.5 on 2023-10-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0032_order_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product_offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
