# Generated by Django 4.2.5 on 2023-10-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0033_category_offer_is_active_coupon_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
