# Generated by Django 4.2.5 on 2023-10-20 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0035_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='expiration_date',
            new_name='date',
        ),
    ]
