# Generated by Django 4.2.5 on 2023-10-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0036_rename_expiration_date_message_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_with_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=255)),
            ],
        ),
    ]
