# Generated by Django 4.2.5 on 2023-10-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0038_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_users',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
